### ISSUE TITLE
Not installing on Ubuntu 16.04

### ISSUE THREAD

**Issue by ccimrie** [JIC-CSB/kilombo#35]
I'm trying to install Kilombo and when running the command sudo make install I get these errors:

```
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcheck.a(check_log.o): In function `subunit_lfun':
(.text+0x584): undefined reference to `subunit_test_start'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcheck.a(check_log.o): In function `subunit_lfun':
(.text+0x63f): undefined reference to `subunit_test_fail'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcheck.a(check_log.o): In function `subunit_lfun':
(.text+0x654): undefined reference to `subunit_test_pass'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcheck.a(check_log.o): In function `subunit_lfun':
(.text+0x66f): undefined reference to `subunit_test_error'
collect2: error: ld returned 1 exit status
src/tests/CMakeFiles/check_skilobot.dir/build.make:172: recipe for target 'src/tests/check_skilobot' failed
make[2]: *** [src/tests/check_skilobot] Error 1
CMakeFiles/Makefile2:181: recipe for target 'src/tests/CMakeFiles/check_skilobot.dir/all' failed
make[1]: *** [src/tests/CMakeFiles/check_skilobot.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

Not sure if I'm doing something silly or if I'm missing something obvious.

**Comment by fjansson** [comment]
Thank you for reporting this. We can reproduce the problem. Apparently something changed in the libcheck shipped with Ubuntu 16.04, in the linking flags needed.

https://github.com/libcheck/check/issues/60

**Comment by AmayaSasaki** [comment]
Hi,
I get the same problem when running sudo make install on Debian 4.9.65-3+deb9u2. What should I do?

**Comment by fjansson** [comment]
How about not building the tests by default? 
The problem is that libcheck, which we use for tests was changed and this broke the build. We could update our build scripts but then it would probably break for those still having the old version of the library. 

My first hunch would be to remove enable_testing() from CMakelists.txt, maybe it builds then. Please let us know if this works.

**Comment by fjansson** [comment]
There's also pull request https://github.com/JIC-CSB/kilombo/pull/40 which should fix this - We didn't apply it generally since is looks like it would break the build for others.

**Comment by AmayaSasaki** [comment]
Thanks. However I removed enable_testing() from CMakelists.txt but still get the same error...

**Comment by Adam01010101F** [comment]
Same here. I am on Ubuntu 17.10 

`(.text+0x5f4):` undefined reference to `subunit_test_start'
(.text+0x6bf): undefined reference to `subunit_test_fail'
(.text+0x6d4): undefined reference to `subunit_test_pass'
(.text+0x6ef): undefined reference to `subunit_test_error'
collect2: error: ld returned 1 exit status
src/tests/CMakeFiles/check_skilobot.dir/build.make:172: recipe for target 'src/tests/check_skilobot' failed
make[2]: *** [src/tests/check_skilobot] Error 1
CMakeFiles/Makefile2:181: recipe for target 'src/tests/CMakeFiles/check_skilobot.dir/all' failed
make[1]: *** [src/tests/CMakeFiles/check_skilobot.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error `2`

Is what I am getting. I have tried removing enable_testing() from the Cmake but that doesn't help and I've also created the Cmake from the pull request #40. Neither of them have helped. I still get errors.

**Comment by Adam01010101F** [comment]
@fjansson The workaround seemed to work. In response to the changes I did last time, the errors remained the same. I only cloned the base project on master, so I am assuming that it wasn't included? I am a noob when it comes to cMake, how would I go about making sure it is installed?

**Comment by fjansson** [comment]
Subunit is a separate library. It is not included in kilombo, but can be installed with the ubuntu package manager, probably like this (this installs check too, if not already there):
```
sudo aptitude install subunit check
```

**Comment by AmayaSasaki** [comment]
It works fine for me (Debian 4.9). Thanks.

**Comment by fjansson** [comment]
Looks good to me. I still want to test on OSX and Arch linux, where subunit previously wasn't needed, just to see what cmake does when target_link_libraries adds a library which isn't installed. 

On fedora the new branch works. Subunit-devel is a dependency of check-devel, so subunit is installed automatically. I'll add the fedora commands to the readme too.

**Comment by fjansson** [comment]
It appears the patch would make subunit a requirement on all systems. I'd like to avoid this.

I just committed a different construction, which tries to find subunit, and adds it to the library list only if it was found. So on systems where subunit isn't required by check (like Arch Linux) it is now not a dependency. If someone could test this on Ubuntu, and it works also there, I think we can merge into master.

The subunit-finding script is from [here](https://github.com/babelouest/ulfius/blob/master/cmake-modules/FindSubunit.cmake) .

**Comment by tjelvar-olsson** [comment]
So should this bug be marked as fixed with fc742d6?

**Comment by fjansson** [comment]
Yes, fixed with fc742d6 . Thanks all for reporting and testing!
